schemas:
  LD_HEALTH_MONTHLY:
   columns:
   - QUALITY_SERVICE
   - PRACTICE_CODE
   - PRACTICE_NAME
   - PCN_ODS_CODE
   - PCN_NAME
   - ONS_SUB_ICB_LOC_CODE
   - SUB_ICB_LOC_CODE
   - SUB_ICB_LOC_NAME
   - ONS_ICB_CODE
   - ICB_CODE
   - ICB_NAME
   - ONS_COMM_REGION_CODE
   - COMM_REGION_CODE
   - COMM_REGION_NAME
   - ACH_DATE
   - IND_CODE
   - MEASURE
   - VALUE

  LD_HEALTH_MONTHLY_DICTIONARY_INDICATORS:
   columns:
   - QUALITY_SERVICE_ID
   - QUALITY_SERVICE_NAME
   - IND_CODE
   - IND_DESCRIPTION

  LD_HEALTH_MONTHLY_DICTIONARY_MEASURES:
   columns:
   - MEASURE
   - MEASURE_DESCRIPTION
   - MEASURE_TYPE