schemas:
  MH_SERVICES_OOA_ACUTE:
    columns:
    - REPORTING_PERIOD_START
    - REPORTING_PERIOD_END
    - STATUS
    - BREAKDOWN
    - PRIMARY_LEVEL
    - PRIMARY_LEVEL_DESCRIPTION
    - SECONDARY_LEVEL
    - SECONDARY_LEVEL_DESCRIPTION
    - MEASURE_ID
    - MEASURE_NAME
    - MEASURE_VALUE

  MH_SERVICES_OOA_NON_ACUTE:
    columns:
    - REPORTING_PERIOD_START
    - REPORTING_PERIOD_END
    - STATUS
    - BREAKDOWN
    - PRIMARY_LEVEL
    - PRIMARY_LEVEL_DESCRIPTION
    - SECONDARY_LEVEL
    - SECONDARY_LEVEL_DESCRIPTION
    - MEASURE_ID
    - MEASURE_NAME
    - MEASURE_VALUE

  MH_SERVICES_PERFORMANCE:
    columns:
    - REPORTING_PERIOD_START
    - REPORTING_PERIOD_END
    - STATUS
    - BREAKDOWN
    - PRIMARY_LEVEL
    - PRIMARY_LEVEL_DESCRIPTION
    - SECONDARY_LEVEL
    - SECONDARY_LEVEL_DESCRIPTION
    - MEASURE_ID
    - MEASURE_NAME
    - MEASURE_VALUE

  MH_SERVICES_RESTRICTIVE:
    columns:
    - REPORTING_PERIOD_START
    - REPORTING_PERIOD_END
    - STATUS
    - BREAKDOWN
    - LEVEL_ONE
    - LEVEL_ONE_DESCRIPTION
    - LEVEL_TWO
    - LEVEL_TWO_DESCRIPTION
    - LEVEL_THREE
    - LEVEL_THREE_DESCRIPTION
    - LEVEL_FOUR
    - LEVEL_FOUR_DESCRIPTION
    - LEVEL_FIVE
    - LEVEL_FIVE_DESCRIPTION
    - LEVEL_SIX
    - LEVEL_SIX_DESCRIPTION
    - METRIC
    - METRIC_VALUE